{"name": "Создание пользователя который уже есть в системе", "status": "passed", "description": "При создании дублирующего пользователя срабатывает allert ", "start": 1739735815859, "stop": 1739735815934, "uuid": "28d4f4ee-40b7-4da7-8d45-7a4e82a7ecf0", "historyId": "511af5c3d1ba0594e424965a597653ae", "testCaseId": "511af5c3d1ba0594e424965a597653ae", "fullName": "tests.test_create_user.TestCreateUser#test_create_double_user_error", "labels": [{"name": "suite", "value": "Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "nb-122695"}, {"name": "thread", "value": "20624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}