{"name": "Авторизация под пользователем, который есть в системе", "status": "passed", "description": "При авторизация под пользователем, который есть в системе, происходит успешная авторизация", "start": 1739735819194, "stop": 1739735819337, "uuid": "7fca0a28-9757-454c-ba16-9329ffde548d", "historyId": "c1ee95458348aabac0acb25665322199", "testCaseId": "c1ee95458348aabac0acb25665322199", "fullName": "tests.test_login_user.Testlogin#test_login_user", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "nb-122695"}, {"name": "thread", "value": "20624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}